// <auto-generated />
using System;
using IncentivePayTracker.API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncentivePayTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncentivePayTracker.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExempted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmployeeInfraction", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("InfractionId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "InfractionId", "Month", "Year");

                    b.HasIndex("InfractionId");

                    b.ToTable("EmployeeInfractions");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmployeeTimeIn", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeIn")
                        .HasColumnType("time");

                    b.HasKey("EmployeeId", "Month", "Year");

                    b.ToTable("EmployeeTimeIns");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmploymentDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("MonthHired")
                        .HasColumnType("int");

                    b.Property<int?>("MonthTerminated")
                        .HasColumnType("int");

                    b.Property<int>("YearHired")
                        .HasColumnType("int");

                    b.Property<int?>("YearTerminated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmploymentDates");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.Infraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Infractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200.0,
                            Description = "If you are missing a login and/or logout in Sprout during a work day."
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200.0,
                            Description = "If you forget to log your hours in JIRA (or equivalent methods in your project) and send the report by 4PM the following work day.\r\n\r\nIf you forget to log your hours before you go on a planned leave."
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200.0,
                            Description = "If your login time in Sprout is past your latest allowed login time."
                        },
                        new
                        {
                            Id = 4,
                            Amount = 500.0,
                            Description = "If you take a leave of absence (vacation leave) without respecting the proper advance notice period. \r\n\r\nIf you take a leave of absence with no notification at all (AWOL)"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 300.0,
                            Description = "If you take an undertime, SL, or Compensation, but did not file it or clearly declare whether it's for deduction or compensation, that Marifil has to chase you for it.\r\n\r\n(Check https://tinyurl.com/p862fcx3 for proper filing of these absences)."
                        },
                        new
                        {
                            Id = 6,
                            Amount = 500.0,
                            Description = "If you were sick for 2 days without a medical certificate, or submit it late that Jobi has to chase you for it. \r\n\r\nIf you file your SL late (over 1 working day after returning from SL)."
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1000.0,
                            Description = "If you are unavailable during project activities without giving timely notification."
                        },
                        new
                        {
                            Id = 8,
                            Amount = 200.0,
                            Description = "If you miss submitting an evaluation feedback (including self-evaluation) before a deadline."
                        },
                        new
                        {
                            Id = 9,
                            Amount = 500.0,
                            Description = "If you miss submitting an evaluation feedback (including self-evaluation) before a second or an extended deadline."
                        });
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmployeeInfraction", b =>
                {
                    b.HasOne("IncentivePayTracker.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncentivePayTracker.API.Models.Infraction", "Infraction")
                        .WithMany()
                        .HasForeignKey("InfractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Infraction");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmployeeTimeIn", b =>
                {
                    b.HasOne("IncentivePayTracker.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IncentivePayTracker.API.Models.EmploymentDate", b =>
                {
                    b.HasOne("IncentivePayTracker.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
